# Generated by Django 2.0.9 on 2018-10-19 19:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20181019_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliopage',
            name='portfolio_cards',
            field=wagtail.core.fields.StreamField([('portfolio_cards', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('headline', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False))]))]),
        ),
    ]
